on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List Forks of current repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |  
          FORKS=$(gh repo list elc9aya2ls612j --json parent,name -q '.[] | select(.parent != null and .parent.name == "fork-me") | .name')
          # Loop through the forks
          for FORK in $FORKS; do
            echo $FORK is the current fork
            # Clone the fork
            gh repo clone "elc9aya2ls612j/$FORK"
            cd $FORK
            git remote -v
            # Fetch the upstream
            git fetch upstream
            # Checkout the main branch
            git checkout main
            # Merge the upstream
            git merge upstream/main
            # Push the changes
            git push
            # Go back to the parent repo
            cd ..
          done
          
      