on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List Forks of current repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |  
          FORKS=$(gh repo list elc9aya2ls612j --json parent,name -q '.[] | select(.parent != null and .parent.name == "fork-me") | .name')
          # Loop through the forks
          while read -r $FORK; do
            # Clone the fork
            gh repo clone "elc9aya2ls612j/$FORK"
            # Add the upstream remote
            cd $FORK
            git remote add upstream https://github.com/elc9aya2ls612j/fork-me.git
            # Fetch the upstream
            git fetch upstream
            # Checkout the main branch
            git checkout main
            # Merge the upstream
            git merge upstream/main
            # Push the changes
            git push
            # Go back to the parent repo
            cd ..
          done <<< "$FORKS"
          
      